name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
	build:
    name: Build app
		runs-on: ubuntu-latest
		steps:
    - uses: actions/checkout@v2
    - name: configure
		  run: ./configure        
	  - name: make
 			run: make
