name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
	build:
<<<<<<< HEAD
	name: Build app
	    runs-on: ubuntu-latest
	    steps:
	    - uses: actions/checkout@v2
	    - name: configure
	   	  run: ./configure        
	    - name: make
 			  run: make
=======
    name: Build app
		runs-on: ubuntu-latest
		steps:
    - uses: actions/checkout@v2
    - name: configure
		  run: ./configure        
	  - name: make
 			run: make
>>>>>>> de718ef723a5b58093e5f4519af698727f0a22b2
