name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Make
      run: make

  deploy:

    runs-on: macos-latest
    needs: build

    steps:
      - name: Packing
        run: | 
          mkdir tasker
          chmod +x tsk
          mv tsk tasker
          ls tasker
          ./tasker/tsk

      - name: Upload
        uses: actions/upload-artifact@v2
        with: 
          name: takser-0.0.1-${{ github.run_id }}
          path: tasker
