name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Assembly for MacOS 11
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Make
      run: make

    - name: Packing
      run: | 
        mkdir tasker
        chmod +x tsk
        mv tsk tasker
        ls tasker
        ./tasker/tsk

    - name: Upload
      uses: actions/upload-artifact@v2
      with: 
        name: takser-0.0.1-${{ github.run_id }}.MacOS-11
        path: tasker